### ISSUE TITLE
Task get_meeting_reports fails silently

### ISSUE THREAD

**Issue by SilverBull** [ucla/moodle-mod_zoom#102]
Hello, 
I'm getting this silent error, the task run correctly once, since then I only receive `Execute scheduled task: Ricevi da Zoom il report sulla riunione (mod_zoom\task\get_meeting_reports)` and it's marked error from Moodle task log.
I tried to launch it from cli with ` /usr/bin/php  /var/www/html/moodle/admin/tool/task/cli/schedule_task.php --execute=\\mod_zoom\\task\\get_meeting_reports --showdebugging` but it doesn't show anything else, if I enable the task to run in cron it block the cron and even with debugging `$CFG->showcrondebugging = true;` it doesn't show any message.

The same is applied to \mod_zoom\task\update_meetings with the only difference being that this task never worked

I run Moodle 3.8.2 and the plugin is updated to the last release

**Comment by jrchamp** [comment]
Is it possible that you are hitting the same problem as #84? There are some hard-coded English strings that the code tests against.

**Comment by SilverBull** [comment]
How can I verify this? Yes my zoom is localized in italian so it's plausible but still it worked once.

**Comment by jrchamp** [comment]
I'm not sure where the best place to start would be. For me, I'd dig into the code and put debug output every few lines of code to see where it stopped working. When programs stop running, it's usually because: there was a fatal error, someone used `exit()`/`die()` or there was an uncaught Throwable/Exception.

- Fatal errors will usually print output if you enable all errors via `error_reporting(-1);` and output standard errors via `ini_set('log_errors', 1);`
- Uncaught Exceptions will usually print output like fatal errors, but you can use something like `try { code_that_is_throwing_an_exception(); } catch (Exception $e) { echo $e->getMessage(); echo $e->getTraceAsString(); }` to inspect it a bit closer if the default exception handler is hiding it from you.
- `die()` and `exit()` often need to be tracked down by a deep dive in the code (unless you are using something like xdebug that will let you know where they are hiding)

**Comment by SilverBull** [comment]
Yes I know how to debug in generally, I was meaning where the place to start debugging the get_meeting_reports task inherent to the language discussion that you linked. I mean the task calls the locallib.php ?

**Comment by jrchamp** [comment]
I'm thinking it's not related now that I've taken a closer look at the code. I don't see any obvious connections between these static-language functions and the task code:

- zoom_is_meeting_gone_error
- zoom_is_user_not_found_error
- autocreate_user
- zoom_delete_instance

Sorry!

**Comment by SilverBull** [comment]
No problem :) I'm setting up a clone so I can debug freely and eventually report

**Comment by rlorenzo** [comment]
Hopefully fixed in https://github.com/ucla/moodle-mod_zoom/commit/5f4a2fd15fbffe80a05a6e54948609fcb8a265b4
