### ISSUE TITLE
Zoom webservice error: Invalid access token..

### ISSUE THREAD

**Issue by urmilapol** [ucla/moodle-mod_zoom#105]

**Comment by urmilapol** [comment]
when i have to integrate moodle it shows this error

**Comment by urmilapol** [comment]
Zoom webservice error: Invalid access token..

**Comment by rlorenzo** [comment]
Make sure you have an Educational/Business Zoom account and setup a JWT app.

Also, on the Zoom developer forum (https://devforum.zoom.us/):

-----
JWT/SDK Token invalid error (To fix, deactivate and activate your JWT/SDK App)

We are aware of the Invalid access token. when using a SDK / JWT Token to call the Zoom APIs. Our engineering team is working on fixing this issue and we will update the status here once the issue is resolved. Thank you for your patience.
-----

If you are getting invalid token errors the workaround is to deactivate and then activate your JWT app.
