### ISSUE TITLE
Feature request - duplicate

### ISSUE THREAD

**Issue by georgmaisser** [ucla/moodle-mod_zoom#124]
When I duplicate a zoom activity which is marked as "recurring" I would expect that the link to the original meeting stays the same. Right now, duplication always creates a new link, although in Zoom it is possible to schedule a recurring meeting with always the same link. Would be great to include this feature in the module.

**Comment by rlorenzo** [comment]
@georgmaisser That would be a headache..  Because suppose you have two meetings with the same link. But then you delete of the meetings. What should happen? Leave other course module with a broken link? Regenerate the link for the other course module? Or don't delete the meeting on Zoom if the link exists on another module? 

If it is the last option, we would have to keep track of meeting links when deleting... it isn't clean.

So when we duplicate we duplicate the meeting settings and not the link.
