### ISSUE TITLE
Add the option to use username (or mapped field) instead of email

### ISSUE THREAD

**Issue by nexterday** [ucla/moodle-mod_zoom#178]
for institutes with Shibboleth or exchange (as an example), the unified userID is usually added as username (or any other mapped field of choice) and is different than the "randomly" added email and its being used as a unique real identifier.

A setting option of which field to use as an identifier is needed in this case. right now previous users (and even new ones) of zoom, get new user data generated because their email (which they dont use for login) is being registered with zoom.

**Comment by jonlan** [comment]
We would really like to make this possible.
We can not use the Zoom Plugin as we did last semester because the Zoom E-Mail address can no longer be adjusted by the user to match it with the Moodle E-Mail address.

**Comment by rlorenzo** [comment]
@nexterday @jonlan Unfortunately that is the limitation of the Zoom API. See https://marketplace.zoom.us/docs/api-reference/zoom-api/users/user

The userId is either the Zoom user ID or the email address of the user. The API does not allow another identifier. If this changes in the Zoom API then we can certainly allow this. We also hate having to use email to identify users since people can change their email address.

**Comment by nexterday** [comment]
There must be a misunderstanding. We do not want to change zoom api, we want to have the option to select another field instead of email field, and we are responsible for the data we add in the field.

**Comment by rlorenzo** [comment]
@nexterday From my understanding of the Zoom API it only uses email or Zoom user ID. Even if you populate another field with your unique identifier it is not used in the Zoom APIs.

**Comment by nexterday** [comment]
We plan to use the field to add an email address anyway, its not that we want to use the field to add a telephone number
