### ISSUE TITLE
Bug Calendar event type action

### ISSUE THREAD

**Issue by rvenema** [ucla/moodle-mod_zoom#179]
Hey team, 

I installed the Zoom plugin version 3.4 on a Totara environment version 12, Moodle 3.3.9 (Build: 20181112). I  ran into an error, zee the attached image: 
![image (7)](https://user-images.githubusercontent.com/77274246/104595803-632c2f80-5673-11eb-8592-ab589a6b3cab.png)

Version 2.2. of the plugin works on this environment. However, version 3.4 does not work. Are there changes that could cause this error? And is this something that will remain in the plugin (this means Totara customers eventually cannot use the plugin anymore)?

Thank you for your help in advance!

Robin

**Comment by jrchamp** [comment]
The CALENDAR_EVENT_TYPE_ACTION constant was added to Moodle prior to the release of 3.3.0. It's possible that the constant is not define in that context. Competencies has a require_once to make sure that the constant is defined: https://github.com/moodle/moodle/commit/4477520e5a05c782ab50607fe97658c7213ae4ed

**Comment by rlorenzo** [comment]
Totara is not really Moodle since it forked. They must not have the Competencies framework as do the newest version of Moodle. I don't have Totora or the codebase to look at... @rvenema ask Totora for help or if you can make a patch to check for CALENDAR_EVENT_TYPE_ACTION existing I can accept that. But right now only Moodle proper is supported by this plugin.
