### ISSUE TITLE
Plugins Zoom meeting and slow Cron jobs

### ISSUE THREAD

**Issue by mfoinf** [ucla/moodle-mod_zoom#185]
Hello!
I'm writing to you regarding the Moodle plugin Zoom meeting, https://moodle.org/plugins/pluginversion.php?id=23076
 
We are using this plugin version 3.1, but have problems with the cron jobs.
 
\mod_zoom\task\update_meetings runs by default every 30 minutes. It always takes longer than 30 minutes and we have 
now changed so that this cron job instead always runs once at night. Is it possible to speed up update_meetings, so that it does not delay all other cron jobs?
 
Even \mod_zoom\task\get_meeting_reports which runs by default every 6 hours takes a long time and it also delays other cron jobs.
Is it possible to speed it up? We have now changed, so that this also runs at night.
 
We also wonder what the consequences will be of these croon jobs being run less often than usual.
 
Regards Marie Fors, Linneuniversitetet

**Comment by rlorenzo** [comment]
The v3.4 plugin now uses the Dashboard API which uses fewer API calls than the Reporting API that Zoom provides. However, there was a bug with it that was just fixed in https://github.com/ucla/moodle-mod_zoom/commit/9987cf7bc1347f17ec7a2c590a906faef2484946

If you run the current master code it will include the patch. A new version will be released once a few more of the active pull requests are merged in
