### ISSUE TITLE
Course Restore issue if Zoom is not available

### ISSUE THREAD

**Issue by mhughes2k** [ucla/moodle-mod_zoom#205]
If Zoom isn't configured it looks like the Zoom plugin causes a restore to completely fail:
![image](https://user-images.githubusercontent.com/694841/108227995-5ac58980-7136-11eb-8dc5-a3f9e7fae20d.png)

**Comment by jrchamp** [comment]
Quick nitpick on the title, because the Zoom module is "available" (code is present), but not "configured" (trying to use it throws an exception).

Whether or not it is correct, the exception is coming from here:
https://github.com/ucla/moodle-mod_zoom/blob/228d213d5bf3768914859d41ab2030132840d2c1/classes/webservice.php#L126

This gets into a philosophical question about data integrity. If all content must be restored without error, but the current behavior is frustratingly correct. If content cannot be restored and throws an exception, then if content that cannot be restored is marked as failed but the restore should continue, then we have to convince Moodle to handle these exceptions, likely as part of the restore_structure_step.

If instead, we just want Zoom to fail gracefully (and not tell Moodle that any dependent content also failed), then the place that would need to catch and handle the exception would probably be:
https://github.com/ucla/moodle-mod_zoom/blob/228d213d5bf3768914859d41ab2030132840d2c1/backup/moodle2/restore_zoom_stepslib.php#L64

If Moodle's gradebook is an indication of their philosophy (all or nothing), then the current behavior is correct and the users need to uncheck the Zoom activities when creating the backup. 😕

**Comment by rlorenzo** [comment]
@mhughes2k This is the same error we get when we try to restore other 3rd party tools like TurnItIn. It is better for someone to uncheck the Zoom activity when they are either backing up or restoring. Silently failing wouldn't be good, since it can lead people to think that everything got restored.
