### ISSUE TITLE
Zoom API v2: new branch to push request

### ISSUE THREAD

**Issue by tigusigalpa** [ucla/moodle-mod_zoom#23]
Hi!
I maked new version of your Zoom.us Moodle plugin on my forked branch:
- API v2 support
- Licenses management

Can you plaese make a branch for it to make a request?

**Comment by anatolyg7** [comment]
@rlorenzo Rex, can you help us integrate the changes we made to this plugin (API v2 suuport and automatic Pro license assignment) into your baseline code. We prefer it this way rather than making separate plugin.
Thanks

**Comment by rlorenzo** [comment]
@tigusigalpa @anatolyg7 Can you please submit a pull request for just the APIv2 support and then a separate one for the license management? What is licenses management?

**Comment by rlorenzo** [comment]
@tigusigalpa @anatolyg7 I see the commit here: https://github.com/tigusigalpa/moodle-mod_zoom/commit/c2c5a6615a063c6c66c05cdd73ec97158c9e8fbf

How does the license management work?

**Comment by anatolyg7** [comment]
License management is a feature that allows educational institution to fully utilize 20 available Zoom Pro licenses by automatically assigning Pro license to meeting initiator (meeting initiatated from Moodle). It also should check that there are available unassigned licenses and if there are none - it will unassign license from user who didn't use Zoom for a longest time.

This is how Zoom itself proposes to use education license, this feature is implementation of this proposal

**Comment by rlorenzo** [comment]
That's very neat. What happens to any reoccurring meetings/etc? Does the user who loses their pro license get anything deleted from their account? Just want to understand the implications of losing a license and if we want to enable or disable this feature for us.

**Comment by anatolyg7** [comment]
When user license is changed from free to pro - this user loses nothing other than usual restrictions of free license. But you can always manually assign him Pro license back. We will also make a special setting - names of users who should not be left without Pro license (plugin will not touch those users no matter how long ago they used Zoom).
As for recurring meetings - we'll have to think how to support them properly. Maybe a separate scheduled task is needed for this.

**Comment by rlorenzo** [comment]
@tigusigalpa I added some code commits at https://github.com/tigusigalpa/moodle-mod_zoom/commit/c2c5a6615a063c6c66c05cdd73ec97158c9e8fbf

Can they be addressed?

@anatolyg7 Can the license management feature be disabled? Or have a setting for it to be disabled? At our University Moodle is not the only way people get provisioned a Zoom license. Rather than having to maintain a list of users that should not have their license removed we would rather disable this feature.

**Comment by anatolyg7** [comment]
@rlorenzo Yes, a good idea to add a setting to enable/disable automatic license management

**Comment by rlorenzo** [comment]
@anatolyg7 Would you or @tigusigalpa be able to provide a patch that does such that?

**Comment by tigusigalpa** [comment]
Hi @rlorenzo 
Yes, of course the feature of licenses is an option-based in the plugin settings. Sorry, i dint see this discuss till today.

**Comment by rlorenzo** [comment]
@tigusigalpa How do you turn off license management? You just set the value to zero? Looking at the code it seems like it would make the function _make_utmost() always return false and it will not go into the license management code. That is correct, right?

Also, if we turn it off can it also not make the call to get_active_paid_users()? It seems that it can be an expensive call, since it is getting a list of all the users on Zoom and looping through them. We can have that list be 50,000 or more on our system.

**Comment by tigusigalpa** [comment]
@rlorenzo 

> Looking at the code it seems like it would make the function _make_utmost() always return false and it will not go into the license management code. That is correct, right?

No, its not. return false happens only if the statement inside the function is false, usual code.

**Comment by tigusigalpa** [comment]
@rlorenzo you can make a review of the code, of course you as an author can have some corrections, this is normal

**Comment by rlorenzo** [comment]
@tigusigalpa I did make a review. Can you make the changes requested?

**Comment by rlorenzo** [comment]
Yes please cut V1 support

**Comment by tigusigalpa** [comment]
yeah, i cutted V1 support

**Comment by rlorenzo** [comment]
@tigusigalpa I see you did that in https://github.com/tigusigalpa/moodle-mod_zoom/commits/zoomapiv2. Looks good. What is missing is the config setting to let us turn off the license management feature. Can you add that as well?

**Comment by rlorenzo** [comment]
@tigusigalpa I see the setting. From the code I see that in classes/webservice.php the setting utmost ($this->_config->utmost) is checked after get_active_paid_users() is called. But get_active_paid_users() is an expensive function call. It calls list_users(), which returns all the users in Zoom and then it looks through them all to count how many verified accounts there are of a given type.

Can you change the code so that if checks to see if utmost is enabled first before many any other function calls? Any further API calls should not need to be made if the feature is turned off.

**Comment by tigusigalpa** [comment]
Yes, @rlorenzo You absolutely right. Sorry for delay. I maked a Moodle-based cache storage for users list and updated a commit to one final commit. Please take a look

**Comment by rlorenzo** [comment]
@tigusigalpa I see the caching here: https://github.com/tigusigalpa/moodle-mod_zoom/commit/97b39763118b6b22ef823bbf811452342e9d39c7

I see that you made a scheduled task that clears the mod_zoom|user cache every 12 hours. But the odd thing is that the cache is defined as a session cache and that is only valid for the duration of a user's login session: https://docs.moodle.org/dev/The_Moodle_Universal_Cache_(MUC)#Session_cache

So the cache is not going to work as you expect. It will usually always be cleared for every user because their logins are not going to last 12 hours, usually.

Why have the cache be session? The pro users aren't going to different between users, might as well make it an application cache.

Also, you don't need to do a schedule task to clear the cache, you can do the same thing by adding a "time to live" value on the cache by adding the following to the cache definition:
'ttl' => 43200 // 12 hrs in seconds

But also this newest patch does not address the issue I had in the my previous comment that the code to get the list of users and finding who has pro accounts should not be executed if the setting is off. The function "_make_utmost()" should be rewritten as follows:

`
    protected function _make_utmost($type = 2) {
        if (!$this->_config->utmost) {
             return false;
        }
        if ($paid_users = $this->get_active_paid_users($type)) {
            return (count($paid_users) >= $this->_limitfrom);
        }
        return false;
    }
`

**Comment by tigusigalpa** [comment]
Hi, i realised your issues, please take a look. Also feel free to modify the code as you wish

**Comment by johanverweij** [comment]
is there an update or a simple way to get these new things in my moodle? im a noob im sorry ... i only know how to install an module ...... i'm havin problems with the plugin and support at zoom can't help.... because this plugin is not of them.... so they asked me to get some help here....
when i add an first meeting in my moodle i'll get an joinlink .... okay so far.... when i look at my meetings at zoom.us it's placed still everything okay.... but when i want to schedule an futere new meeting in my moodle it will place on my moodle website but with the meeting id / joinlink from the first meeting..... this is going wrong ;) and when i'll look again at my meetings on zoom.us the first meetings is changed to the second meeting on my moodle and the first is gone..... so moodle changes only the time / description but dont get a new id from zoom.us  can somebody please help this noob with this (for me) huge problem....

greetings,
johan

**Comment by rlorenzo** [comment]
We have cleaned the contributed branch and merged it to our master: https://github.com/ucla/moodle-mod_zoom/commit/df46a0b2ab2818c18ec0f7edb758d186287f703e

We will be releasing a new version containing this update soon after we finish a couple more Zoom related bug fixes and improvements.
