### ISSUE TITLE
Better documentation on steps to get developer API

### ISSUE THREAD

**Issue by dirkcgrunwald** [ucla/moodle-mod_zoom#24]
I'm trying to install mod_zoom for moodle. Our campus has a campus-wide license for Zoom.

When I go to my Zoom profile, I have a mechanism to generate an api key & secret. However, that key/secret doesn't work (according to mod_zoom).

When I try to follow the link on the README.md about setting up key & secret, I get to their developer page (briefly) and then get flipped to a page saying I don't have permission or access.

Clearly, when I first approached our local IT staff admins about using Zoom through LTI a year ago, they set something up that allowed me to have the API key, but I don't have any permissions to do what is needed by mod_zoom.

It would be useful to clearly indicate what permissions are needed so that I can communicate it to our central IT organization. I suspect our IT have limited experience because no one else is integrating Zoom into an LMS and thus explicit directions of the needed permissions would reduce the time needed to have them configure it.

**Comment by rlorenzo** [comment]
Hey Dirk, I updated our README. The link has changed.

> See https://developer.zoom.us/docs/api/ and follow the link to "Get your API key pair from here (https://developer.zoom.us/me/#api)"

> You will need to have Zoom administrator access. Please note that the API key and secret is not the same as the LTI key/secret.

The API key/secret is not the same as the LTI key/secret. Do you know who your Zoom Account Admin is?

**Comment by dirkcgrunwald** [comment]
That link also takes me to a page that tells me 

> You do not have permission to view this page.
> Please contact your Zoom Account Admin to enable access for your User/Account.

The Zoom user profile lists the account owner as mcbogg at colorado.edu, account #122238

When making the API key, I'm assuming there's a set of priv's that can be set - is there a recommended list that's sufficient but secure?

Does the mod_zoom module provide more / better features than the LTI interface? I never got that working, so was hoping this was easier / better.

**Comment by rlorenzo** [comment]
Zoom will automatically generate the API key/secret for you.

We tried the LTI integration and it did not quite work for us. So we made the plugin. Some advantages is that we can generate reports of attendance and create meetings with settings such as start time and tie into the gradebook.

**Comment by frumbert** [comment]
Is the documentation for this current? The mentioned link "https://marketplace.zoom.us/docs/api/" leads to this page:

![Screen Shot 2020-04-06 at 5 09 34 pm](https://user-images.githubusercontent.com/592257/78531777-6e6f4680-7829-11ea-9ce0-b849ca1299bd.png)

The adjacent link https://developer.zoom.us/me/#api leads to

![Screen Shot 2020-04-06 at 5 10 01 pm](https://user-images.githubusercontent.com/592257/78531829-847d0700-7829-11ea-8095-514ec433dca4.png)

There are keys at the bottom of my administrators profile page but they don't work either

![My_Settings_-_Zoom](https://user-images.githubusercontent.com/592257/78531917-b8582c80-7829-11ea-9474-91c1e692f07a.jpg)

I guess your documentation should point to https://marketplace.zoom.us/docs/guides ?

I also presume I need to make a JWT app, since it mentions server-side connections. E.g. https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-jwt-app

The only place I've been able to find mention of "APIKEY" on the zoom site is on the Marketplace (https://marketplace.zoom.us/). This has a Develop menu, where I can choose Build App. APIKEY here is mentioned on the JWT area. 

Clicking the Create button and entering any name results in the error being displayed at the top of the browser:

![Screen Shot 2020-04-06 at 5 08 42 pm](https://user-images.githubusercontent.com/592257/78531719-50a1e180-7829-11ea-9483-15f9c019fa3e.png)

Therefore I can't create an apikey. Can you please clear up your documentation?

**Comment by rlorenzo** [comment]
@frumbert Does this link work to clarify things? https://marketplace.zoom.us/docs/guides/auth/jwt

But note:

> Note: As account-level apps, JWT apps require Developer Role Permission to create, edit or access.

**Comment by frumbert** [comment]
As it turns out there has been an ongoing issue creating new jwt tokens, which has been failing intermittently for a few days. It's working for some, not for most. I managed to generate one once and then when I tried again it was broken again.
