### ISSUE TITLE
Feature request: Zoom plugin should be able to use the zoom account of the first entering user

### ISSUE THREAD

**Issue by cdipe** [ucla/moodle-mod_zoom#49]
The problem is that a user can have only one meeting at a time. Thus, a teacher cannot set up scheduled meetings where several student groups should have their own meetings. 
In fact the teacher can only set up meetings that she is sure she will attend themself, otherwise if she starts another meeting it might upset a meeting she has scheduled for the students in a Moodle course. 
Instead our teachers are now using Skype For Business or Adobe Connect (both systems allow for several meetings at a time) to arrange such meetings. We want them to use Zoom all the time though, for the benefit of our users just having to use ONE system for e-meetings.

**Suggestion:** 
Develop the plugin with an option that the first user entering the sceduled meeting initiates his/her own zoom account for the meeting, instead of using the teacher's/meeting arrangers account.

**Comment by jrchamp** [comment]
Background: Currently, the plugin schedules the meeting for the user who adds the activity, when they add the activity. The Meeting shows up in the web, desktop client and app for the activity creator. Users can join outside of Moodle if they have the Meeting ID.

For this suggestion: It requires that students have their own Zoom accounts (with a Pro license if the student group has more than two people and they want to be able to meet for more than 40 minutes). It also would need to schedule the Meeting on demand. Unfortunately, that would also make the first person to join the Host (which conflicts with typical use case of a "class meeting"). Given that the one-meeting-at-a-time limit is coming from Zoom, we're somewhat talking about adding an optional on-demand scheduling feature that is off by default (so as not to break the existing experience for instructors). This may also be a good fit when combined with the "separate by groups" option.

As alternatives:

- If the students have Zoom Pro accounts already, they can schedule the meeting directly through Zoom (via web, desktop client or app).
- If the instructor wants to give the students the ability to create Zoom activities through Moodle, they can override the student role at the course level to give them the "add instance" capability so that students can schedule their own group meetings from within Moodle.

**Comment by rlorenzo** [comment]
Closing as "wouldn't do" for the reasons above.
