### ISSUE TITLE
Zoom home page URL

### ISSUE THREAD

**Issue by frumbert** [ucla/moodle-mod_zoom#86]
What is the Zoom Home Page Url?

Where inside https://zoom.us/account do I look to find it? 

Where is the documentation for these settings?

**Comment by rlorenzo** [comment]
@frumbert This plugin is intended for users with business or educational Zoom accounts. Such accounts get a special Zoom URL for their users. For us it is https://ucla.zoom.us. So that is what this config is for. To redirect users to your Zoom instance so they can login and have a Zoom account created.
