### ISSUE TITLE
Zoom Module settings error message

### ISSUE THREAD

**Issue by barry-matthias** [ucla/moodle-mod_zoom#87]
When accessing the zoom configuration page the following is being shown:

Connection status: Connection failed: Invalid access token.

**Comment by DavidDelco** [comment]
Hi,
I experienced the same problem, did you resolve it?
Thank you

**Comment by barry-matthias** [comment]
Hi David

Not yet as there are 3 possibilities which could cause the issue and i cant seem to get hold of either the module developer and or the zoom support teams to determine which is causing it.
At present we are bypassing this module altogether by using an LTI connection to zoom back end servers. What we do next will be determined by the outcome of this test.

regards

**Comment by DavidDelco** [comment]
Hi Matthias,
Thanks for the reply. Since I'm not an IT technician, I have full confidence in what you tell me. While waiting for a solution to be found, I will continue to publish the meeting link within the course. ;-)
Best regards

**Comment by rlorenzo** [comment]
I saw this on the Zoom developer forum (https://devforum.zoom.us/):

-----
JWT/SDK Token invalid error (To fix, deactivate and activate your JWT/SDK App)

We are aware of the Invalid access token. when using a SDK / JWT Token to call the Zoom APIs. Our engineering team is working on fixing this issue and we will update the status here once the issue is resolved. Thank you for your patience.
-----

If you are getting invalid token errors the workaround is to deactivate and then activate your JWT app.
